export const locationNames = [
  'United States',
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Washington,D.C',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire', 
  'New Jersey', 
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota', 
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island', 
  'South Carolina',
  'South Dakota', 
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

// This object remains unchanged as it is the source of truth
export const locations: { [key: string]: number } = {
  'United States': 0,
  'Oregon': 33,
  'Alaska': 49,
  'Michigan': 26,
  'Kansas': 34,
  'New Mexico': 47,
  'Delaware': 1,
  'Arizona': 48,
  'Alabama': 22,
  'Ohio': 17,
  'Pennsylvania': 2,
  'Nebraska': 37,
  'New Jersey': 3,
  'Colorado': 38,
  'Missouri': 24,
  'Massachusetts': 6,
  'Rhode Island': 13,
  'Connecticut': 5,
  'South Carolina': 8,
  'Montana': 41,
  'Maine': 23,
  'Wisconsin': 30,
  'South Dakota': 40,
  'Arkansas': 25,
  'Indiana': 19,
  'Kentucky': 15,
  'North Dakota': 39,
  'West Virginia': 35,
  'Louisiana': 18,
  'Mississippi': 20,
  'Idaho': 43,
  'North Carolina': 12,
  'Florida': 27,
  'Minnesota': 32,
  'Oklahoma': 46,
  'Hawaii': 50,
  'Illinois': 21,
  'Washington': 42,
  'Tennessee': 16,
  'Nevada': 36,
  'Utah': 45,
  'Maryland': 7,
  'Wyoming': 44,
  'California': 31,
  'New York': 11,
  'Virginia': 10,
  'Vermont': 14,
  'Iowa': 29,
  'Texas': 28,
  'Georgia': 4,
  'New Hampshire': 9,
  'Washington,D.C': 51
}
export const months:{[key:number]:string} = {
  1:'January',2:'February',3:'March',4:'April', 5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'
}